### ISSUE TITLE
install-spring-batch won't work on windows because of use of ':' delimeter in the classpath which conflicts with the ':' in 'C:\'

### ISSUE THREAD

**Issue by quentinburley** [radcortez/wildfly-spring-batch#1]
See the following error that occurs when attempting to run in windows:

mvn process-resources wildfly:execute-commands -P install-spring-batch

Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.0.1.Final:execute-commands (default-cli) on project wildfly-spring-batch: Execution default-cli of goal org.wildfly.plugins:wildfly-maven-plugin:1.0.1.Final:execute-commands failed: Failed to process file 'C:\Users\user\NetBeansProjects\wildfly-spring-batch\target\scripts\wildfly-add-spring-batch.cli': Command execution failed for command '    --resources=C:\Users\user\.m2\repository\org\codehaus\jettison\jettison\1.2\jettison-1.2.jar:C:\Users\user\.m2\repository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar

etc.. etc..

I suspect because of  ':' delimeter in the classpath which conflicts with the ':' in 'C:\'

Anyone ever attempted to something similar in windows?

**Comment by quentinburley** [comment]
OK.. I note that in pom.xml:
configuration for maven-dependency-plugin contains:
<pathSeparator>:</pathSeparator>

This is best removed as by default pathSeparator assumes the correct system specific value.

This solves the issue for me.

**Comment by radcortez** [comment]
Awesome! Thank you very much for trying and submitting the PR :)
